## Hub | Server | Both
Mode: Hub

## Web client configuration
Kestrel:
  EndPoints:
    Http:
      Url: http://localhost:17250
AllowedHosts: "*"
Logging:
  LogLevel:
    Default: Information
    Microsoft: Information
    Microsoft.AspNetCore: Warning

## Database configuration
Database:
  Type: Sqlite
  Store: Data Source=app.db;cache=shared
  InMemory: "DataSource=file:app.db?mode=memory&cache=shared"
  Persist: true
  PersistDuration: 86400

## Card configuration
Cards:
  Allowed:
    - EPC-GEN1
    - EPC-GEN2
    - ISO1800-6B
  TruncateNumber: 0
  MaximumLength: 24

## IOT Hub mode
Hub:
  Enable: true
  Auto: true
  Store: true
  Forward: true
  Protocol: KingJoin
  MinFrequency: 120
  PersistDuration: 86400
  Connections:
    Retries: 5
    Timeout: 3
    ## Serial | Network | Both
    Type: Serial
    Serial:
      Enable: true
      Id: SITE-01
      ## Common serial port defaults
      # Windows: COM5 | Linux: /dev/ttyUSB0 | Mac: /dev/tty.usbserial-*
      PortName: "null"
      BaudRate: 9600
      DataBits: 8
    ## Hub ethernet configurations
    Network:
      Enable: false
      Id: SITE-01
      Type: TCP
      Address: 127.0.0.1
      Port: 56000

## Server mode configuration
Server:
  Enable: false
  Store: true
  Forward: false
  Protocols:
    - Name: Chafon
      Type: TCP
      Port: 17301
    - Name: KingJoin
      Type: UDP
      Port: 17302

## Web forwarding configuration
Forward:
  Enable: true
  Path: "http://localhost:40440/proton.frequency.service/api/v1/log"
  Method: POST
  Auth: false
  Username: ""
  Password: ""
  MaxDelay: 1
  Frequency: 7
  Buffer: 10
  Network:
    Verify: true
    Ping: google.com
    Timeout: 100
