net-client:
  - id: client-00
    type: chafon
    host: 192.168.0.201
    port: 1730
  - id: client-01
    type: kjoin
    host: 192.168.0.202
    port: 1732
  - id: client-02
    type: kjoin
    host: 192.168.0.203
    port: 1733