allowedHosts: "*"
system:
  name: "Proton.Frequency"
  web: true
  api: true
  port: 7001
  terminal: false
  network: false
  secret: secret
  event: true
  resources: false
  queue:
    enable: true
    port: 1883
database:
  type: sqlite
  store: "Data Source=app.sqlite3;cache=shared"
  persist: 86400
logging:
  logLevel:
    default: Information
    microsoft: Information
    microsoft.AspNetCore: Warning
