service:
  management: true
  api: true
  proxy: false
  network: false
  secret: secret
  event: true
database:
  type: sqlite
  store: "Data Source=app.sqlite3;cache=shared"
  persist: true
  persistDuration: 86400
logging:
  logLevel:
    default: Information
    microsoft: Information
    microsoft.AspNetCore: Warning
