terminal:
  id: unit-default
  channel: default
  host: 127.0.0.1
  port: 7002
  auto: false
  retries: 5
  timeout: 3
  queue:
    host: 127.0.0.1
    port: 1883
    sync: true
    timeout: 3
    retry: 5
serial:
  - id: serial-one
    type: chafon
    port: /dev/ttyUSB0
    rate: 9600
    bits: 8
  - id: serial-two
    type: kjoin
    port: /dev/ttyUSB1
tag:
  max: 256
  allowed:
    - EPC-GEN1
    - EPC-GEN2
    - ISO1800
  