networks:
  - name: reader-00
    protocol: chafon
    port: 1731
  - name: reader-01
    protocol: king-join
    port: 1732
  - name: nfc-00
    protocol: king-join
    port: 1733
  - name: client-00
    protocol: custom-0
    Port: 1734
    server: true
