### Frequency.Device default options #####
Logging:
  LogLevel:
    Default: Information
    Microsoft: Information
    Microsoft.AspNetCore: Warning

AllowedHosts: "*"

Kestrel:
  EndPoints:
    Http:
      Url: "http://localhost:5010"

## Database configuration
Database:
  Type: Sqlite
  Store: Data Source=app.db;cache=shared
  InMemory: "DataSource=file:app.db?mode=memory&cache=shared"
  Persist: true
  PersistDuration: 86400

## IOT Terminal mode
Device:
  Auto: false
  Connections:
    Retries: 5
    Timeout: 3

## Card configuration
Cards:
  Allowed:
    - EPC-GEN1
    - EPC-GEN2
    - ISO1800-6B

## Web forwarding configuration
Forward:
  Enable: true
  ## 'http://frequency.test:40440/service/api/v1/log?id={terminal.id}&tag-id={tag.id}'
  Path: "http://frequency.test:40440/service/api/v1/log"
  Method: POST
  Auth: false
  Username: ""
  Password: ""
  Frequency: 15
  Timeout: 3
  Retry: 5
  Buffer: 10
  Delay: 300
  Network:
    Verify: true
    Ping: google.com
    Timeout: 5

Management:
  Host: "frequency.test"
  Port: 8080
  EndPoints:
    Config: "management/config"
    StateSync: "management/state"
