### Frequency.Device default options #####

AllowedHosts: "*"

Logging:
  LogLevel:
    Default: Information
    Microsoft: Information
    Microsoft.AspNetCore: Warning

Kestrel:
  EndPoints:
    Http:
      Url: "http://localhost:5010"

Management:
  Host: "frequency.test/api"
  Port: 8080
  EndPoints:
    Config: "management/config"
    StateSync: "management/state"

## Database configuration
Database:
  Type: Sqlite
  Store: Data Source=app.db;cache=shared
  InMemory: "DataSource=file:app.db?mode=memory&cache=shared"
  Persist: true
  PersistDuration: 86400

## IOT Node defaults
Device:
  Auto: false
  Connections:
    Retries: 5
    Timeout: 3

## Card configuration
Card:
  MaxLength: 256
  Allowed:
    - EPC-GEN1
    - EPC-GEN2
    - ISO1800-6B

## Web forwarding configuration
Forward:
  Enable: true
  ## http://frequency.test:40440/service/api/v1/log?id={terminal.id}&tag-id={tag.id}
  Path: "http://frequency.test:40440/service/api/v1/log"
  Method: POST
  Auth:
    Type: Basic
    Username: test
    Password: test
    Token: xxxx-xxxx-xxxx-xxxx
  Frequency: 15
  Timeout: 3
  Retry: 5
  Buffer: 10
  Delay: 300
  Network:
    Verify: true
    Ping: google.com
    Timeout: 5
