name: Publish Proton.Frequency

on:
  push:
    paths-ignore:
      - "docs/**"
      - ".config/**"
      - "CHANGELOG.md"
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup required packages
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl libicu-dev

      - name: Install .NET 7.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "7.0.x"
          include-prerelease: true
      - name: Install .NET 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: Build, Test, Pack, Publish
        shell: bash
        run: |
          dotnet tool restore
          dotnet dotnet-releaser run --force --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml
